name: Linting and Unit Tests for PaaS Deployments API

on: push

jobs:
  test:
    name: Lint and Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm run lint:ts
    - run: npm run test

